CREATE TABLE tipo_tramite (
    id          NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(120)   NOT NULL UNIQUE,
    requisitos  VARCHAR2(1000),
    cupo_diario NUMBER(10)      NOT NULL,
    activo      NUMBER(1)       DEFAULT 1 NOT NULL
);
